- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-victoria-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
    gate:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # NOTE(TheJulia): high-ish failure rate due to memory footprint,
        # Commenting out for now.
        # - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
