- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-yoga-jobs
      - openstack-python3-yoga-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-cross-sushy:
            voting: false
        - ironic-tempest-functional-python3
        - ironic-standalone:
            voting: false
        - ironic-standalone-redfish:
            voting: false
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-partition-bios-ipmi-pxe
        - ironic-tempest-partition-uefi-ipmi-pxe
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
    gate:
      jobs:
        # NOTE(TheJulia): Return this to voting once
        # https://review.opendev.org/c/openstack/ironic/+/910528
        # or similar change to the branch has merged
        #- ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        #- ironic-tempest-functional-rbac-scope-enforced
        # NOTE(TheJulia): Disabling because of weird networking failures
        # on standalone job, also redfish handles the bulk of the need.
        # - ironic-standalone
        # - ironic-standalone-redfish
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-partition-bios-ipmi-pxe
        - ironic-tempest-partition-uefi-ipmi-pxe
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
    experimental:
      jobs:
        # TODO(dtantsur): these jobs are useful but currently hopelessly
        # broken. Fix them and bring back to the gate.
        - ironic-tempest-ipxe-ipv6:
            voting: false
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
