- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-wallaby-jobs
      - openstack-python3-wallaby-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - metalsmith-integration-glance-localboot-centos8-uefi
        # Non-voting jobs
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
    gate:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - metalsmith-integration-glance-localboot-centos8-uefi
